Controllers/BookController.cs
using Library.Models;
using Org.BouncyCastle.Tls;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        Library_ManagementEntities1 libentities = new Library_ManagementEntities1();

        public ActionResult BookGenres(int? c)
        {
            List<Book_Genre> bookgenre = libentities.Book_Genre.ToList();
            return View(libentities.Book_Genre.ToList().ToPagedList(c ?? 1,6));
        }

        //[Route("Index/{GenreId}")]
        public ActionResult Index(int? GenreId)
        {
            List<Book> book = libentities.Books.Where(bk => bk.GenreId == GenreId).ToList();
            return View(book);
        }
        public ActionResult Index1(int? GenreId)
        {
            List<Book> book = libentities.Books.Where(bk => bk.GenreId == GenreId).ToList();
            return View(book);
        }
        public ActionResult Create()
        {
            List<Book_Genre> genre = libentities.Book_Genre.ToList();
            ViewBag.Book_Genre = new SelectList(genre, "GenreId", "Genre");
            ViewBag.ReturnUrl = Request.UrlReferrer;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase Picture, [Bind(Include = "BookName,Author,GenreId,Available")] Book book)
        {
            if (ModelState.IsValid)
            {
                byte[] cover;

                using (var reader = new BinaryReader(Picture.InputStream))
                {
                    cover = reader.ReadBytes(Picture.ContentLength);
                }
                book.Picture = cover;
                libentities.Books.Add(book);
                libentities.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            Book book = libentities.Books.Find(id);
            ViewBag.ReturnUrl = Request.UrlReferrer;
            return View(book);
        }

        public ActionResult Edit(int? id)
        {
            Book book = libentities.Books.Find(id);
            List<Book_Genre> genre = libentities.Book_Genre.ToList();
            ViewBag.Book_Genre = new SelectList(genre, "GenreId", "Genre");
            ViewBag.ReturnUrl = Request.UrlReferrer;
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase Picture, [Bind(Include = "BookId,BookName,Author,GenreId,Available")] Book book)
        {
            if (ModelState.IsValid)
            {
                byte[] cover;

                using (var reader = new BinaryReader(Picture.InputStream))
                {
                    cover = reader.ReadBytes(Picture.ContentLength);
                }
                book.Picture = cover;
                libentities.Entry(book).State = System.Data.Entity.EntityState.Modified;
                libentities.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Delete(int? id)
        {
            Book book = libentities.Books.Find(id);
            ViewBag.ReturnUrl = Request.UrlReferrer;
            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = libentities.Books.Find(id);
            libentities.Books.Remove(book);
            libentities.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult TakeBook(int? id)
        {
            Book book = libentities.Books.Find(id);
            TempData["BookID"] = book.BookId;
            TempData["Bookname"] = book.BookName;
            TempData["Picture"] = book.Picture;
            TempData["userid"] = Session["userID"];
            ViewBag.ReturnUrl = Request.UrlReferrer;
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TakeBook( [Bind(Include = "TakeId,UserId,Username,Email,BookId,BookName,TakenDate,ReturnDate,IsReturned")] Book_Taken booktaken )
        {
            int? userId = TempData["userid"] as int?;
            string username = Session["name"] as string;
            string email = Session["email"] as string;
            int? BookId = TempData["BookID"] as int?;
            string Bookname = TempData["Bookname"] as string;
            byte[] Pic = TempData["Picture"] as byte[];

            if (ModelState.IsValid)
            {
                booktaken.UserId = userId;
                booktaken.Username = username;
                booktaken.Email = email;
                booktaken.BookId = BookId;
                booktaken.BookName = Bookname;
                booktaken.TakenDate = DateTime.Now;
                booktaken.ReturnDate = DateTime.Now.AddDays(14);
                booktaken.Picture = Pic;
                booktaken.IsReturned = false;
                libentities.Book_Taken.Add(booktaken);
                libentities.SaveChanges();
                return RedirectToAction("Index1", "BookTaken");
            }
            return View();
        }

        public class SearchResult
        {
            public Nullable<int> Id { get; set; }
            public string Name { get; set; }
            public Nullable<int> Available { get; set; }
            public string Author { get; set; }
            public byte[] Image { get; set; }
        }

        public ActionResult SearchBook(string name)
        {
            var searchResults = new SearchResult();

            var booksAndAuthors = libentities.Books
                .Where(b => b.BookName.Contains(name) || b.Author.Contains(name))
                .Select(b => new { Id = b.BookId, Name = b.BookName, Available = b.Available, Author = b.Author, Image = b.Picture }).ToList();

            searchResults.Name = booksAndAuthors.First().Name;
            searchResults.Author = booksAndAuthors.First().Author;
            searchResults.Id = booksAndAuthors.First().Id;
            searchResults.Available = booksAndAuthors.First().Available;
            searchResults.Image = booksAndAuthors.First().Image;

            if (searchResults.Id!=null)
            {
                if (User.IsInRole("Librarian"))
                {
                    return View("Search1", searchResults);
                }
                else
                {
                    return View("Search2", searchResults);
                }
            }
            else
            {
                return RedirectToAction("BookGenres");
            }
        }

        public ActionResult Search1()
        {
            return View();
        }

        public ActionResult Search2()
        {
            return View();
        }
    }
}

Controllers/FineController.cs
using Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class FineController : Controller
    {
        Library_ManagementEntities1 libentities = new Library_ManagementEntities1();
        public ActionResult Index(int? a)
        {
            List<Fine> fine = libentities.Fines.ToList();
            return View(libentities.Fines.ToList().ToPagedList(a ?? 1,5));
        }
        public ActionResult Index1(int? b)
        {
            List<Fine> fine = libentities.Fines.ToList();
            return View(libentities.Fines.ToList().ToPagedList(b ?? 1, 5));
        }

        public class OrderModel
        {
            public string orderId { get; set; }
            public string razorpayKey { get; set; }
            public int amount { get; set; }
            public string currency { get; set; }
            public string name { get; set; }
            public string email { get; set; }
            public int fineId { get; set; }
        }


        [HttpPost]
        public ActionResult CreateOrder(Fine _fndata)
        {
            Random randomObj = new Random();
            string transactionId = randomObj.Next(10000000, 100000000).ToString();
            Razorpay.Api.RazorpayClient payClient = new Razorpay.Api.RazorpayClient("rzp_test_0ISuvn0T3DxvYV", "8xvT8EUGg3p056yzibjM4BvK");
            Dictionary<string, object> options = new Dictionary<string, object>();
            options.Add("amount", _fndata.FineAmount * 100);
            options.Add("receipt", transactionId);
            options.Add("currency", "INR");
            options.Add("payment_capture", "0");
            Razorpay.Api.Order orderResponse = payClient.Order.Create(options);
            string orderId = orderResponse["id"].ToString();

            OrderModel order = new OrderModel
            {
                orderId = orderResponse.Attributes["id"],
                razorpayKey = "rzp_test_0ISuvn0T3DxvYV",
                amount = (int)_fndata.FineAmount * 100,
                currency = "INR",
                name = _fndata.Username,
                email = _fndata.Email,
                fineId = _fndata.FineId
            };

            return View("Payment", order);
        }

        [HttpPost]
        public ActionResult Payment(int fineid)
        {
            string paymentId = Request.Params["rzp_paymentid"];
            string orderId = Request.Params["rzp_orderid"];
            Razorpay.Api.RazorpayClient payClient = new Razorpay.Api.RazorpayClient("rzp_test_0ISuvn0T3DxvYV", "8xvT8EUGg3p056yzibjM4BvK");
            Razorpay.Api.Payment payment = payClient.Payment.Fetch(paymentId);
            Dictionary<string, object> options = new Dictionary<string, object>();
            options.Add("amount", payment.Attributes["amount"]);
            Razorpay.Api.Payment paymentCaptured = payment.Capture(options);
            string amt = paymentCaptured.Attributes["amount"];
            if (paymentCaptured.Attributes["status"] == "captured")
            {
                Fine fine = libentities.Fines.Find(fineid);
                fine.IsPaid = true;
                libentities.SaveChanges();
                return RedirectToAction("Success");
            }
            else
            {
                return RedirectToAction("Failure");
            }
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Failed()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            Fine fine = libentities.Fines.Find(id);
            return View(fine);
        }
    }
}

Controllers/UserController.cs
using Library.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;
using PagedList.Mvc;

namespace Library.Controllers
{
    public class UserController : Controller
    {
        Library_ManagementEntities1 libentities = new Library_ManagementEntities1();

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(User user)
        {
            Validate_User_Result roleUser = libentities.Validate_User(user.Email, user.Password).FirstOrDefault();
            string message = string.Empty;
            switch (roleUser.UserId.Value)
            {
                case -1:
                    message = "Email / Password is incorrect.";
                    break;
                case -2:
                    message = "Account has not been activated.";
                    break;
                default:
                    Session["userID"] = roleUser.UserId;
                    List<User> userData = libentities.Users.ToList();
                    foreach (User users in userData)
                    {
                        if (roleUser.UserId == users.UserId)
                        {
                            Session["name"] = users.Username;
                            Session["email"] = users.Email;
                            Session["Avatar"] = users.Avatar;
                        }
                    }
                    FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1, user.Email, DateTime.Now, DateTime.Now.AddMinutes(30), false, roleUser.Roles, FormsAuthentication.FormsCookiePath);
                    string hash = FormsAuthentication.Encrypt(ticket);
                    HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, hash);
                    if (ticket.IsPersistent)
                    {
                        cookie.Expires = ticket.Expiration;
                    }
                    Response.Cookies.Add(cookie);
                    libentities.GenerateFine();
                    return RedirectToAction("Index", "Home");
            }
            ViewBag.Message = message;
            return View(user);
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(HttpPostedFileBase Avatar, [Bind(Include = "UserId,Username,RoleId,Password,Email")] User newUser)
        {
            if (ModelState.IsValid)
            {
                byte[] pic;
                using (var reader = new BinaryReader(Avatar.InputStream))
                {
                    pic = reader.ReadBytes(Avatar.ContentLength);
                }
                newUser.Avatar = pic;
                libentities.Users.Add(newUser);
                libentities.SaveChanges();
                return RedirectToAction("Login");
            }
            return View();
        }

        [Authorize(Roles = "Librarian")]
        public ActionResult Index(string search, int? i)
        {
            List<User> user = libentities.Users.ToList();
            return View(libentities.Users.Where(x => x.Username.StartsWith(search)
            || search == null).ToList().ToPagedList(i ?? 1,3));
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            User user = libentities.Users.Find(id);
            return View(user);
        }

        public ActionResult Edit(int? id)
        {
            User user = libentities.Users.Find(id);
            List<Role> role = libentities.Roles.ToList();
            ViewBag.Roles = new SelectList(role, "RoleId", "RoleName");
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase Avatar, [Bind(Include = "UserId,Username,RoleId,Password,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                byte[] edpic;
                using (var reader = new BinaryReader(Avatar.InputStream))
                {
                    edpic = reader.ReadBytes(Avatar.ContentLength);
                }
                user.Avatar = edpic;
                libentities.Entry(user).State = System.Data.Entity.EntityState.Modified;
                libentities.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Delete(int? id)
        {
            User user = libentities.Users.Find(id);
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = libentities.Users.Find(id);
            libentities.Users.Remove(user);
            libentities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditProfile(int? id)
        {
            User user = libentities.Users.Find(id);
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProfile(User updatedUser, HttpPostedFileBase updatedAvatar)
        {
            if (ModelState.IsValid)
            {
                User currentuser = libentities.Users.Find(updatedUser.UserId);

                if (currentuser != null)
                {
                    currentuser.Username = updatedUser.Username;
                    currentuser.Email = updatedUser.Email;
                    if (updatedAvatar != null && updatedAvatar.ContentLength > 0)
                    {
                        using (var reader = new BinaryReader(updatedAvatar.InputStream))
                        {
                            currentuser.Avatar = reader.ReadBytes(updatedAvatar.ContentLength);
                        }
                    }
                    libentities.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(updatedUser);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Public Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/d7200c44d8.js" crossorigin="anonymous"></script>
</head>
<body>
    @{ 
        @Html.Partial("_Navbar")
    }
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p id="footer">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr.js"></script>
    @RenderSection("scripts", required: false)

<style>
   #footer {
      font-weight: 700;
      font-size: 14px;
   }
</style>

</body>
</html>

Views/Shared/_Navbar.cshtml
<div class="navbar navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                <i class="fa-solid fa-bars" id="hamburger"></i>
            </button>
            <img src="@Url.Content("~/Content/images/logo.gif")" style="width:100px;height:80px" />
        </div>
        @if (User.Identity.IsAuthenticated)
        {
            byte[] Profile = Session["Avatar"] as byte[];
            if (User.IsInRole("Librarian"))
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                        <li>@Html.ActionLink("Books", "BookGenres", "Book")</li>
                        <li>@Html.ActionLink("Books Taken", "Index", "BookTaken")</li>
                        <li>@Html.ActionLink("Penalty", "Index", "Fine")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="data:image;base64,@Convert.ToBase64String(Profile)" class="img-circle pic" alt="Avatar" />
                                @Session["name"]  <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("EditProfile","User", new {id = Session["userID"]})"><i class="fa-solid fa-user-pen" style="color: #000000;"></i> Edit Profile</a></li>
                                <li><a href="@Url.Action("Logout","User")"><i class="fa-solid fa-right-from-bracket" style="color: #000000;"></i> Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            }
            if (User.IsInRole("User"))
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Books", "BookGenres", "Book")</li>
                        <li>@Html.ActionLink("Books Taken", "Index1", "BookTaken")</li>
                        <li>@Html.ActionLink("Penalty", "Index1", "Fine")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="data:image;base64,@Convert.ToBase64String(Profile)" class="img-circle pic" alt="Avatar" />
                                @Session["name"]  <i class="fa fa-caret-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("EditProfile","User", new {id = Session["userID"]})"><i class="fa-solid fa-user-pen" style="color: #000000;"></i> Edit Profile</a></li>
                                <li><a href="@Url.Action("Logout","User")"><i class="fa-solid fa-right-from-bracket" style="color: #000000;"></i> Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            }
        }
        else
        {
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Register", "Register", "User")</li>
                    <li>@Html.ActionLink("Login", "Index", "User")</li>
                </ul>
            </div>
        }
    </div>
</div>

<style>
    #hamburger {
        color: darkblue;
        font-size: 2em !important;
    }

    .navbar {
        background-color: #AED2FF;
        color: darkgrey;
    }

    .navbar-nav li a {
        font-size: 16px;
        margin-top: 1em;
        margin-left: .5em;
        font-weight: bold;
        color: dimgrey;
    }

    .pic {
        width: 45px;
        height: 40px;
        padding-right: 5px;
    }
</style>